package publish

import (
	"archive/zip"
	"context"
	"database/sql"
	"errors"
	"fmt"
	"path/filepath"
	"slices"
	"strings"

	"github.com/bioclimamx/conagua-etl/internal/archive"
)

// MaxTopLevelFiles is Zenodo's per-record file cap, the binding
// constraint of the artifact set: the deposit's top-level file count
// must never exceed it. The 79-file set
// — two archives for each of the 32 states, four national archives, the
// raw snapshot, and the ten docs — fits with room, and the arithmetic is
// pinned by a spec rather than hoped; a build that would leave more
// files in the deposit directory is refused.
const MaxTopLevelFiles = 100

// StateArchive is one per-state archive that built successfully in this
// run — the source a copy-built national archive reads its per-station
// and per-cell files from.
type StateArchive struct {
	State State
	Path  string
}

// NationalEntries is the assembly of a copy-built national archive: the
// entries archive.WriteZipMixed takes, Path-sorted, and the number of
// units among them — one per state archive consumed. The copied entries
// read from the state archives opened during assembly, which stay open
// until Close; the caller runs Close once the write has finished, on
// failure too.
type NationalEntries struct {
	Entries []archive.MixedEntry
	Units   int
	sources []*zip.ReadCloser
}

// Close releases the state archives the entries copy from. A second
// call is a no-op.
func (n *NationalEntries) Close() error {
	var errs []error
	for _, s := range n.sources {
		if err := s.Close(); err != nil {
			errs = append(errs, fmt.Errorf("close state archive: %w", err))
		}
	}
	n.sources = nil
	return errors.Join(errs...)
}

// NationalCSVEntries assembles national-csv.zip: every state's
// per-station files (conagua/daily_observations/<slug>/,
// combined/combined_daily/<slug>/) and per-cell files
// (nasa_power/daily/) copied raw from the state tabular archives —
// byte-identical entries, no recompression — a cell several states
// carry once, from the first state in state order, the other states'
// copies held to it by CRC-32 and size; the seven whole-scope tables
// regenerated at national scope (every CONAGUA conventional station in
// external_id order, every referenced cell in cell_id order — the same
// queries every state archive's tables run, without the state
// predicate); and provenance/ once, rendered from runs. The Parquet
// twins and the state databases are not copied: national-parquet.zip
// and national-sqlite.zip regenerate their own. archives are the
// succeeded tabular archives, which must be every state of the DB in
// state order — the national archive is every state's, so a missing
// state refuses the assembly naming it — and each must hold at least
// one file to copy. The state archives are opened now and stay open
// until the returned assembly is closed; the tables query at write
// time. The unit is the state archive consumed: onUnit (optional) fires
// once per archive, labelled by its file name, after the last entry
// copied from it in write order.
func NationalCSVEntries(ctx context.Context, db *sql.DB, archives []StateArchive, runs Runs, onUnit UnitFunc,
) (*NationalEntries, error) {
	own := slices.Concat(tableEntries(ctx, db, nationalScope), ProvenanceEntries(runs))
	return assembleNational(ctx, db, archives, "tabular", tabularEntryClass, own, onUnit)
}

// NationalJSONEntries assembles national-json.zip: every state's
// combined/<slug>/<station_id>/{daily,profile}.json copied raw from the
// state JSON archives, and provenance/ once as JSON, rendered from runs.
// archives are the succeeded JSON archives, under the same rules as
// NationalCSVEntries: every state in state order, each with something
// to copy, opened now and closed with the assembly; the unit is the
// state archive consumed.
func NationalJSONEntries(ctx context.Context, db *sql.DB, archives []StateArchive, runs Runs, onUnit UnitFunc,
) (*NationalEntries, error) {
	return assembleNational(ctx, db, archives, "json", jsonEntryClass, provenanceJSONEntries(runs), onUnit)
}

// entryClass is what the national build does with one entry of a state
// archive it does not regenerate itself.
type entryClass int

const (
	// copyEntry is a per-unit file, copied raw.
	copyEntry entryClass = iota
	// skipEntry is regenerated by another national archive, or by this
	// one, and is not copied.
	skipEntry
)

// classifier decides what to do with one entry of st's archive whose
// path the national archive does not generate itself: copy it, skip it,
// or refuse it — an entry the archive layout does not account for is an
// integrity signal, since a silently skipped file would be a lost one.
type classifier func(st State, name string) (entryClass, error)

// tabularEntryClass sorts a state tabular archive's entries: the
// per-station files under the state's own shard and the per-cell files
// are copied; the Parquet twins and the state database are skipped —
// national-parquet.zip and national-sqlite.zip regenerate their own,
// since a per-state Parquet file is not a shard of the national one;
// anything else — another state's shard, an unknown path — is refused.
func tabularEntryClass(st State, name string) (entryClass, error) {
	switch {
	case strings.HasSuffix(name, ".parquet"), name == stateDBName(st):
		return skipEntry, nil
	case strings.HasPrefix(name, DailyObservations.Name+"/"):
		return shardEntryClass(st, DailyObservations.Name, name)
	case strings.HasPrefix(name, CombinedDaily.Name+"/"):
		return shardEntryClass(st, CombinedDaily.Name, name)
	case strings.HasPrefix(name, PowerDaily.Name+"/"):
		return copyEntry, nil
	}
	return 0, fmt.Errorf("entry %q is not part of a state tabular archive", name)
}

// jsonEntryClass sorts a state JSON archive's entries: the station
// files under the state's own shard (combined/<slug>/, profilePath's
// home) are copied; anything else is refused.
func jsonEntryClass(st State, name string) (entryClass, error) {
	if strings.HasPrefix(name, "combined/") {
		return shardEntryClass(st, "combined", name)
	}
	return 0, fmt.Errorf("entry %q is not part of a state JSON archive", name)
}

// shardEntryClass copies an entry under folder only from the state's
// own shard, <folder>/<slug>/: a state archive carrying another state's
// shard is not this run's archive.
func shardEntryClass(st State, folder, name string) (entryClass, error) {
	if strings.HasPrefix(name, folder+"/"+st.Slug+"/") {
		return copyEntry, nil
	}
	return 0, fmt.Errorf("entry %q is under another state's shard", name)
}

// copiedEntry is one raw copy with the index of the state archive it
// reads from.
type copiedEntry struct {
	entry  archive.MixedEntry
	source int
}

// assembleNational is the copy-built national archive: it holds
// archives to the DB's states, opens each in order, classifies every
// entry — an entry whose path the archive generates itself (own, the
// entries it regenerates rather than copies) is skipped as regenerated,
// the rest per classify — collects the copies, merges them with own
// Path-sorted, and hangs the unit hook on the last entry copied from
// each archive in write order. On any failure the archives opened so
// far are closed and nothing is returned.
func assembleNational(ctx context.Context, db *sql.DB, archives []StateArchive, kind string, classify classifier,
	own []archive.Entry, onUnit UnitFunc,
) (*NationalEntries, error) {
	if err := checkStateArchives(ctx, db, archives, kind); err != nil {
		return nil, err
	}
	regenerated := make(map[string]bool, len(own))
	for _, e := range own {
		regenerated[e.Path] = true
	}
	copied, sources, err := copyStateArchives(ctx, archives, regenerated, classify)
	if err != nil {
		return nil, err
	}
	n := &NationalEntries{Units: len(archives), sources: sources}

	sourceOf := make(map[string]int, len(copied))
	n.Entries = make([]archive.MixedEntry, 0, len(copied)+len(own))
	for _, c := range copied {
		sourceOf[c.entry.Path] = c.source
		n.Entries = append(n.Entries, c.entry)
	}
	for _, e := range own {
		n.Entries = append(n.Entries, archive.Generated(e))
	}
	slices.SortFunc(n.Entries, func(a, b archive.MixedEntry) int { return strings.Compare(a.Path, b.Path) })

	if onUnit != nil {
		// Every archive contributed at least one copy (copyStateArchives
		// refuses one that did not), so each last index is set below.
		last := make([]int, len(archives))
		for i, e := range n.Entries {
			if src, ok := sourceOf[e.Path]; ok {
				last[src] = i
			}
		}
		for src, i := range last {
			label := filepath.Base(archives[src].Path)
			n.Entries[i].Written = func() { onUnit(label) }
		}
	}
	return n, nil
}

// checkStateArchives holds archives to the DB's state list: exactly
// every state, in state order, each once. The national archive is every
// state's, so a state whose archive failed or was never built refuses
// the assembly naming it, and an archive for a state the DB does not
// carry, or out of order, is not this run's set.
func checkStateArchives(ctx context.Context, db *sql.DB, archives []StateArchive, kind string) error {
	states, err := LoadStates(ctx, db)
	if err != nil {
		return err
	}
	want := codes(states)
	got := make([]string, len(archives))
	for i, a := range archives {
		got[i] = a.State.Code
	}
	if slices.Equal(want, got) {
		return nil
	}
	for _, code := range want {
		if !slices.Contains(got, code) {
			return fmt.Errorf("no %s archive for %s: the national archive needs every state's", kind, code)
		}
	}
	for i, code := range got {
		if !slices.Contains(want, code) {
			return fmt.Errorf("%s archive %s is for %s, which is not a state of the database",
				kind, filepath.Base(archives[i].Path), code)
		}
	}
	return fmt.Errorf("%s archives are not in state order (%s; the states are %s)",
		kind, strings.Join(got, ", "), strings.Join(want, ", "))
}

// copyStateArchives opens each archive in order and collects the
// entries to copy: regenerated paths are skipped, the rest are
// classified, and a path several archives carry — a cell shared across
// states — is copied from the first, every later archive's copy held to
// it by CRC-32 and size; a mismatch means two archives of one run
// disagree on one file's content, an integrity error naming the file
// and both archives. An archive contributing nothing to copy is refused:
// it is not a state archive of this layout. ctx is checked before each
// archive. On any failure the archives opened so far are closed.
func copyStateArchives(ctx context.Context, archives []StateArchive, regenerated map[string]bool, classify classifier,
) (copied []copiedEntry, sources []*zip.ReadCloser, err error) {
	closeAll := func() {
		for _, s := range sources {
			_ = s.Close()
		}
	}
	seen := make(map[string]*zip.File)
	owner := make(map[string]int)
	for i, a := range archives {
		if err := ctx.Err(); err != nil {
			closeAll()
			return nil, nil, err
		}
		zr, err := zip.OpenReader(a.Path)
		if err != nil {
			closeAll()
			return nil, nil, fmt.Errorf("open state archive: %w", err)
		}
		sources = append(sources, zr)
		contributed := 0
		for _, f := range zr.File {
			if regenerated[f.Name] {
				continue
			}
			class, err := classify(a.State, f.Name)
			if err != nil {
				closeAll()
				return nil, nil, fmt.Errorf("state archive %s: %w", filepath.Base(a.Path), err)
			}
			if class != copyEntry {
				continue
			}
			if first, dup := seen[f.Name]; dup {
				if first.CRC32 != f.CRC32 || first.UncompressedSize64 != f.UncompressedSize64 {
					closeAll()
					return nil, nil, fmt.Errorf("entry %q differs between %s (crc32 %08x, %d bytes) and %s (crc32 %08x, %d bytes)",
						f.Name, filepath.Base(archives[owner[f.Name]].Path), first.CRC32, first.UncompressedSize64,
						filepath.Base(a.Path), f.CRC32, f.UncompressedSize64)
				}
				continue
			}
			seen[f.Name], owner[f.Name] = f, i
			copied = append(copied, copiedEntry{entry: archive.Copied(f), source: i})
			contributed++
		}
		if contributed == 0 {
			closeAll()
			return nil, nil, fmt.Errorf("state archive %s holds no entry to copy", filepath.Base(a.Path))
		}
	}
	return copied, sources, nil
}
